name: csc342project

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/api/src
    # ports:
    #   - '80:80'
    environment:
      - PORT=80
    env_file:
      - .env

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/vite.config.js:/app/frontend/vite.config.js
      - ./frontend/index.html:/app/frontend/index.html
    ports:
      - '5173:5173'
    # environment:
    #   - PORT=80

  database:
    image: mariadb:latest
    restart: unless-stopped
    ports: 
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - "./database/db_schema:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
